import { NextResponse } from "next/server";
import { adminApp } from "../../../firebaseAdmin";
import { validateApiKey } from "../../../../lib/apiKeys";

function toManifest(widget: Record<string, any>) {
  const id = widget.name || widget.id;

  return {
    id,
    name: widget.name || widget.id,
    title: widget.name || widget.id,
    description: widget.description || "Widget generated by eCanvas",
    version: widget.version || "1.0.0",
    author: widget.author || "Anonymous",
    icon:
      widget.icon ||
      `https://placehold.co/512x512/0f172a/ffffff?text=${encodeURIComponent(
        widget.name || widget.id
      )}`,
    manifestUrl: `/api/widget/${encodeURIComponent(id)}`,
    previewUrl: `/api/widget/${encodeURIComponent(id)}/preview`,
    renderUrl: `/api/widget/${encodeURIComponent(id)}/render`,
    pngUrl: `/api/widget/${encodeURIComponent(id)}/png`,
    capabilities: ["render:html", "render:png", "static:preview"],
    supportedFormats: ["html", "png"],
    preview: widget.preview || "",
    endpoints: {
      manifest: `/api/widget/${encodeURIComponent(id)}`,
      preview: `/api/widget/${encodeURIComponent(id)}/preview`,
      render: `/api/widget/${encodeURIComponent(id)}/render`,
      png: `/api/widget/${encodeURIComponent(id)}/png`,
    },
  };
}

export async function GET(
  request: Request,
  { params }: { params: { id: string } }
) {
  try {
    const apiKey = await validateApiKey(request);
    const db = adminApp.firestore();
    const widgetDoc = await db.collection(apiKey.ownerUid).doc(params.id).get();

    if (!widgetDoc.exists) {
      return NextResponse.json(
        { success: false, error: "Widget not found" },
        { status: 404 }
      );
    }

    return NextResponse.json({
      success: true,
      data: toManifest({
        ...widgetDoc.data(),
        name: params.id,
      }),
    });
  } catch (error) {
    return NextResponse.json(
      {
        success: false,
        error: (error as Error).message,
      },
      { status: 401 }
    );
  }
}
