import { NextResponse } from "next/server";
import { adminApp } from "../../firebaseAdmin";
import { validateApiKey } from "../../../lib/apiKeys";

function toManifest(widget: Record<string, any>) {
  const id = widget.name || widget.id;

  return {
    id,
    name: widget.name || widget.id,
    title: widget.name || widget.id,
    description: widget.description || "Widget generated by eCanvas",
    version: widget.version || "1.0.0",
    author: widget.author || "Anonymous",
    icon:
      widget.icon ||
      `https://placehold.co/512x512/0f172a/ffffff?text=${encodeURIComponent(
        widget.name || widget.id
      )}`,
    manifestUrl: `/api/widget/${encodeURIComponent(id)}`,
    previewUrl: `/api/widget/${encodeURIComponent(id)}/preview`,
    renderUrl: `/api/widget/${encodeURIComponent(id)}/render`,
    pngUrl: `/api/widget/${encodeURIComponent(id)}/png`,
    capabilities: ["render:html", "render:png", "static:preview"],
    supportedFormats: ["html", "png"],
    endpoints: {
      manifest: `/api/widget/${encodeURIComponent(id)}`,
      preview: `/api/widget/${encodeURIComponent(id)}/preview`,
      render: `/api/widget/${encodeURIComponent(id)}/render`,
      png: `/api/widget/${encodeURIComponent(id)}/png`,
    },
    createdAt: widget.createdAt || null,
    updatedAt: widget.updatedAt || null,
  };
}

export async function GET(request: Request) {
  try {
    const apiKey = await validateApiKey(request);
    const db = adminApp.firestore();
    const snapshot = await db.collection(apiKey.ownerUid).get();
    const widgets = snapshot.docs.map((doc) => ({
      ...doc.data(),
      name: doc.id,
    }));

    return NextResponse.json({
      success: true,
      data: widgets.map(toManifest),
      apiKey: apiKey.name,
    });
  } catch (error) {
    return NextResponse.json(
      {
        success: false,
        error: (error as Error).message,
      },
      { status: 401 }
    );
  }
}
